[package]
name = "wasm_post_decryptor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
aes-gcm = "0.10"
hkdf = "0.12"
sha2 = "0.10"
getrandom = { version = "0.2", features = ["js"] }