# Generated by Django 4.1 on 2023-04-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(default=None, max_length=150)),
                ('last_name', models.CharField(default=None, max_length=150)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('dob', models.DateField(default=None, max_length=12)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date-joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last-login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_voter', models.BooleanField(default=False)),
                ('is_council', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('verification_token', models.CharField(default='None', max_length=150, null=True)),
                ('phone_number_verified', models.BooleanField(default=False)),
                ('is_setup', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('negative_strikes', models.IntegerField(default=0)),
                ('positive_actions', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
