# Generated by Django 4.0.3 on 2022-03-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourbitAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dob',
            field=models.DateField(default=None, max_length=8),
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
