# Generated by Django 4.0.3 on 2022-04-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourbitAccounts', '0002_account_dob_account_first_name_account_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(default=None, max_length=12),
        ),
    ]
