# Generated by Django 4.0.4 on 2022-09-28 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.CharField(blank=True, max_length=1000)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('video', models.FileField(blank=True, upload_to='media/')),
                ('body', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bit_type', models.CharField(default='chat', max_length=20)),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('is_tips', models.BooleanField(default=False)),
                ('comment_count', models.IntegerField(default=0)),
                ('contains_video_link', models.BooleanField(default=False)),
                ('contains_news_link', models.BooleanField(default=False)),
                ('contains_web_link', models.BooleanField(default=False)),
                ('extend_widget', models.CharField(blank=True, max_length=1000)),
                ('video_widget', models.CharField(blank=True, max_length=1000)),
                ('bit_background', models.CharField(default='#4b4b4b', max_length=50)),
                ('title_color', models.CharField(default='#ffffff', max_length=50)),
                ('text_color', models.CharField(default='#ffffff', max_length=50)),
                ('feedback_icon_color', models.CharField(default='#ffffff', max_length=50)),
                ('feedback_background_color', models.CharField(default='#313131', max_length=50)),
                ('paragraph_align', models.CharField(default='left', max_length=10)),
                ('accent_color', models.CharField(default='#ffffff', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bits', models.ManyToManyField(blank=True, related_name='clustered_bit', to='social.bit')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default=None, max_length=1000)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('bit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.bit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_uploaded', models.BooleanField(default=False)),
                ('image', models.ImageField(default='media/blenderlogo.png', upload_to='media/')),
                ('background_image', models.ImageField(blank=True, default='media/aqua_default_theme.png', upload_to='media/')),
                ('bit_background', models.CharField(default='#4b4b4b', max_length=50)),
                ('title_color', models.CharField(default='#ffffff', max_length=50)),
                ('text_color', models.CharField(default='#ffffff', max_length=50)),
                ('feedback_icon_color', models.CharField(default='#000000', max_length=50)),
                ('background_color', models.CharField(default='#323232', max_length=50)),
                ('accent_color', models.CharField(default='#ffffff', max_length=50)),
                ('user_bio', models.CharField(blank=True, max_length=500)),
                ('icon_color', models.CharField(default='#ffffff', max_length=50)),
                ('user_colors_on', models.BooleanField(default=True)),
                ('wallpaper_on', models.BooleanField(default=True)),
                ('default_theme_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField(default=0.0)),
                ('item', models.CharField(blank=True, max_length=150)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('image_uploaded', models.BooleanField(default=False)),
                ('image', models.ImageField(default='media/blenderlogo.png', upload_to='media/')),
                ('background_image', models.ImageField(blank=True, default='media/aqua_default_theme.png', upload_to='media/')),
                ('bit_background', models.CharField(default='#4b4b4b', max_length=50)),
                ('title_color', models.CharField(default='#ffffff', max_length=50)),
                ('text_color', models.CharField(default='#ffffff', max_length=50)),
                ('feedback_icon_color', models.CharField(default='#ffffff', max_length=50)),
                ('feedback_background_color', models.CharField(default='#313131', max_length=50)),
                ('paragraph_align', models.CharField(default='left', max_length=10)),
                ('background_color', models.CharField(default='#323232', max_length=50)),
                ('accent_color', models.CharField(default='#ffffff', max_length=50)),
                ('user_bio', models.CharField(blank=True, max_length=500)),
                ('icon_color', models.CharField(default='#ffffff', max_length=50)),
                ('user_colors_on', models.BooleanField(default=True)),
                ('wallpaper_on', models.BooleanField(default=True)),
                ('default_theme_on', models.BooleanField(default=False)),
                ('alerted_notifications', models.BooleanField(default=False)),
                ('rewards_earned', models.IntegerField(default=0)),
                ('share_points', models.IntegerField(default=0)),
                ('point_balance', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('clusters', models.ManyToManyField(blank=True, related_name='clusters', to='social.cluster')),
                ('commented_on', models.ManyToManyField(blank=True, related_name='commented_on', to='social.bit')),
                ('connections', models.ManyToManyField(blank=True, related_name='friends_with', to='social.profile')),
                ('conversations', models.ManyToManyField(blank=True, related_name='conversations', to='social.conversation')),
                ('custom', models.ManyToManyField(blank=True, related_name='custom', to='social.customization')),
                ('disliked_bits', models.ManyToManyField(blank=True, related_name='disliked_bits', to='social.bit')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='social.profile')),
                ('interacted_with', models.ManyToManyField(blank=True, related_name='interacted_with', to='social.bit')),
                ('liked_bits', models.ManyToManyField(blank=True, related_name='liked_bits', to='social.bit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_followers', models.BooleanField(default=False)),
                ('search_by_name', models.BooleanField(default=True)),
                ('real_name_visibility', models.CharField(default='Everyone', max_length=50)),
                ('message_availability', models.CharField(default='Friends Only', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='privacy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_has_seen', models.BooleanField(default=False)),
                ('bit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='social.bit')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='social.comment')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_from', to='social.profile')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_to', to='social.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1500)),
                ('video', models.FileField(blank=True, upload_to='media/message_attachments')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/message_attachments')),
                ('document', models.FileField(upload_to='media/message_files')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='social.conversation')),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends_only_on', models.BooleanField(default=False)),
                ('block_links_on', models.BooleanField(default=False)),
                ('sorting', models.CharField(default='chronological+', max_length=100)),
                ('muted_users', models.ManyToManyField(blank=True, related_name='muted', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='feed', to='social.profile')),
            ],
        ),
        migrations.AddField(
            model_name='customization',
            name='community',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_community', to='social.profile'),
        ),
        migrations.AddField(
            model_name='customization',
            name='profile',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_profile', to='social.profile'),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_by', to='social.community')),
            ],
        ),
        migrations.AddField(
            model_name='cluster',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='social.profile'),
        ),
        migrations.AddField(
            model_name='bit',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='bit_comments', to='social.comment'),
        ),
        migrations.AddField(
            model_name='bit',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bit',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bit',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='social.notification'),
        ),
        migrations.AddField(
            model_name='bit',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_bits', to='social.profile'),
        ),
        migrations.AddField(
            model_name='bit',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bits', to=settings.AUTH_USER_MODEL),
        ),
    ]
