# Generated by Django 4.0.4 on 2022-06-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
    ]
