# Generated by Django 4.0.4 on 2022-07-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(blank=True, default='media/aqua_default_theme.png', upload_to='media/'),
        ),
    ]
