# Generated by Django 4.0.4 on 2022-07-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_profile_level_profile_reward_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='reward_points',
            new_name='point_balance',
        ),
        migrations.AddField(
            model_name='profile',
            name='commented_on',
            field=models.ManyToManyField(blank=True, related_name='commented_on', to='social.bit'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interacted_with',
            field=models.ManyToManyField(blank=True, related_name='interacted_with', to='social.bit'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rewards_earned',
            field=models.IntegerField(default=0),
        ),
    ]
