# Generated by Django 4.0.4 on 2022-07-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_rename_reward_points_profile_point_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends_only_on', models.BooleanField(default=False)),
                ('sorting', models.CharField(default='chronological', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customizations',
            name='background_image',
            field=models.ImageField(blank=True, default='media/aqua_default_theme.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='customizations',
            name='default_theme_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customizations',
            name='image',
            field=models.ImageField(default='media/blenderlogo.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='customizations',
            name='image_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customizations',
            name='user_colors_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customizations',
            name='wallpaper_on',
            field=models.BooleanField(default=True),
        ),
    ]
