# Generated by Django 4.0.4 on 2022-07-21 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_feed_customizations_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='feed', to='social.profile'),
        ),
    ]
