from django.urls import path, re_path
from . import views
from .views import *

urlpatterns = [
    path('home/', Home.as_view(), name='home'),
    path('onboarding/', Onboarding.as_view(), name='onboarding'),
    path('bit/<int:pk>', BitDetailView.as_view(), name='bit-detail'),
    path('bit/<int:pk>/interact/', Interact.as_view(), name='interact'),
    path('profile/<int:pk>/interact', ProfileInteract.as_view(), name='profile-interact'),
    path('profile/<str:username>', ProfileView.as_view(), name="profile"),
    path('mysettings/', Settings.as_view(), name="mysettings"),
    path('personalization/', Personalization.as_view(), name="personalize"),
    path('search/', PreSearch.as_view(), name="search"),
    path('search/results/<str:query>', SearchResults.as_view(), name='search-results'),
    path('messages/', Messages.as_view(), name="messages"),
    path('collection/', MyStuff.as_view(), name="stuff"),
    path('history/<str:action>', HistoryView.as_view(), name="history"),
    path('create/', CreateBit.as_view(), name="create-bit"),
    path('like/', LikeBit.as_view(), name='like'),
    path('dislike/', DislikeBit.as_view(), name='dislike'),
    path('comment/', AddComment.as_view(), name='addComment'),
    path('rewards/', Rewards.as_view(), name='rewards'),
    path('feed/<str:type>/<str:id>/', Feed.as_view(), name='feed'),
    path('test/', DynamicFeedTest.as_view(), name='feedtest'),
    path('visibility/', QuickVisibility.as_view(), name="get-visibility"),
    path('notifications/', GetNotifications.as_view(), name="get-notificatons"),
    path('notifications/status/', NotificationStatus.as_view(), name='get-notification-status'),
    path('publish/', Publish.as_view(), name="publish"),
    path('follow/', Follow.as_view(), name='follow'),
    path('add_friend/', AddFriend.as_view(), name='add-friend'),
    path('notify/', Notify.as_view(), name='notify'),
    path('create-payment-intent/<int:amount>', StripeIntent.as_view(), name='create-payment-intent'),
    path('donate/', Donate.as_view(), name='donate'),
    path('checkout/<int:amount>', Checkout.as_view(), name = 'checkout'),
    path('connections/', ConnectionList.as_view(), name='connections'),
    path('create-conversation', NewConversation.as_view(), name = 'new-conversation'),
]
